AWSTemplateFormatVersion: 2010-09-09
Description: >-
  A main Template for assembly the resource
Parameters:
  TemplateUrlPrefix:
    Type: String
    Default: https://cloudformation-demo.s3.cn-north-1.amazonaws.com.cn
  TagName:
    Type: String
  VpcCidr:
    Type: String
  Subnet1Cidr:
    Type: String
  Subnet2Cidr:
    Type: String
  Subnet3Cidr:
    Type: String
  Subnet4Cidr:
    Type: String
  BasionHostInstanceType:
    Type: String
    Default: t2.large
    AllowedPattern: t2.*
  BasionHostAMI:
    Type: String
  DBPassword:
    Type: String
    NoEcho: 'true'
Resources:
  CreateVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcCidr: !Ref VpcCidr
        TagName: !Ref TagName
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-network-vpc.yaml
      TimeoutInMinutes: 20
  CreateSubnet:
    DependsOn: CreateVpc
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TagName: !Ref TagName
        Subnet1Cidr: !Ref Subnet1Cidr
        Subnet2Cidr: !Ref Subnet2Cidr
        Subnet3Cidr: !Ref Subnet3Cidr
        Subnet4Cidr: !Ref Subnet4Cidr
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-network-subnet.yaml
      TimeoutInMinutes: 20
  CreateGateway:
    DependsOn: CreateVpc
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TagName: !Ref TagName
        DMZSubnet1: !GetAtt CreateSubnet.Outputs.DMZSubnet1
        DMZSubnet2: !GetAtt CreateSubnet.Outputs.DMZSubnet2
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-network-gateway.yaml
      TimeoutInMinutes: 20
  CreateRouteTable:
    DependsOn: CreateVpc
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TagName: !Ref TagName
        DMZSubnet1: !GetAtt CreateSubnet.Outputs.DMZSubnet1
        DMZSubnet2: !GetAtt CreateSubnet.Outputs.DMZSubnet2
        PrivateSubnet1: !GetAtt CreateSubnet.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt CreateSubnet.Outputs.PrivateSubnet2
        NatGateway1: !GetAtt CreateGateway.Outputs.NatGateway1
        NatGateway2: !GetAtt CreateGateway.Outputs.NatGateway2
        InternetGateway: !GetAtt CreateGateway.Outputs.InternetGateway
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-network-routetable.yaml
      TimeoutInMinutes: 20
  CreateEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PublicRouteTable: !GetAtt CreateRouteTable.Outputs.PublicRouteTable
        PrivateRouteTableAZ1: !GetAtt CreateRouteTable.Outputs.PrivateRouteTableAZ1
        PrivateRouteTableAZ2: !GetAtt CreateRouteTable.Outputs.PrivateRouteTableAZ2
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-network-endpoint.yaml
      TimeoutInMinutes: 20
  CreateSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcCidr: !GetAtt CreateVpc.Outputs.VpcCidr
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-network-securitygroup.yaml
      TimeoutInMinutes: 20
  CreateBasion:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BasionHostAMI: !Ref BasionHostAMI
        BasionHostInstanceType: !Ref BasionHostInstanceType
        KeyName: OPS-DEV-TianYuan
        DMZSubnet1: !GetAtt CreateSubnet.Outputs.DMZSubnet1
        TagName: !Ref TagName
        BasionHostSG: !GetAtt CreateSecurityGroup.Outputs.SGBasion
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-other-createbasion.yaml
      TimeoutInMinutes: 20
  CreateAPPServerLaunchTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        LoginSecurityGroupIds: !GetAtt CreateSecurityGroup.Outputs.SGInternalLogin
        WebServerSecurityGroupIds: !GetAtt CreateSecurityGroup.Outputs.SGWebServer
        KeyName: OPS-DEV-TianYuan
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-instance-launchtemplate.yaml
      TimeoutInMinutes: 20
  CreateUserGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-auth-iamuser.yaml
      TimeoutInMinutes: 20
  CreateCodeCommit:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
        CodeBuildSubnet: !GetAtt CreateSubnet.Outputs.PrivateSubnet1
        SecurityGroupIds: !GetAtt CreateSecurityGroup.Outputs.SGInternalLogin
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - ops-deployment-cicd.yaml
      TimeoutInMinutes: 20
  DemoApplication:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        LaunchTemplateId: !GetAtt CreateAPPServerLaunchTemplate.Outputs.InstanceLaunchTemplate
        LaunchTemplateVersion: !GetAtt CreateAPPServerLaunchTemplate.Outputs.InstanceLaunchTemplateVersion
        PrivateSubnet1: !GetAtt CreateSubnet.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt CreateSubnet.Outputs.PrivateSubnet2
        DBPassword: !Ref DBPassword
        VpcId: !GetAtt CreateVpc.Outputs.VpcId
        SGDataBase: !GetAtt CreateSecurityGroup.Outputs.SGDataBase
        SGWebServer: !GetAtt CreateSecurityGroup.Outputs.SGWebServer
      TemplateURL: !Join
                   -  '/'
                   - - !Ref TemplateUrlPrefix
                     - fun-app-demoapp.yaml
      TimeoutInMinutes: 20
