AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC Resource
Parameters:
  VpcCidr:
    Type: String
  TagName:
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Join ['-', [!Ref TagName, 'VPC']]
      - Key: Cost
        Value: Temp-Project
Outputs:
  VpcCidr:
    Value: !Ref VpcCidr
    Description: The Cidr of VPC
  VpcId:
    Value: !Ref VPC