AWSTemplateFormatVersion: 2010-09-09
Description: Create LaunchTemplate for Application
Parameters:
  ApplicationName:
    Type: String
    Default: "TestAPP"
  LoginSecurityGroupIds:
    Type: String
  WebServerSecurityGroupIds:
    Type: String
  KeyName:
    Type: String
Resources:
  CreateLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/sdm
            Ebs:
              VolumeType: gp2
              DeleteOnTermination: 'True'
              VolumeSize: '50'
        ImageId: "ami-08becc383b7267be8"
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref LoginSecurityGroupIds
          - !Ref WebServerSecurityGroupIds
        TagSpecifications:
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: "ApplicationServer Volume"
      LaunchTemplateName: !Join ['-', [!Ref ApplicationName, 'APPServerLaunchTemplate']]
Outputs:
  InstanceLaunchTemplate:
    Value: !Ref CreateLaunchTemplate
    Description: EC2 Instance LaunchTemplate
  InstanceLaunchTemplateVersion:
    Value: !GetAtt CreateLaunchTemplate.LatestVersionNumber
    Description: Launch Template Last Version
